version: '3.8'

services:
  # Apache Service
  www:
    build: docker/php
    container_name: ${APP_SLUG}_apache
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - app_network

  # Mariadb Service
  database:
    image: mariadb:latest
    container_name: ${APP_SLUG}_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: ${APP_ENV}
      SERVICE_NAME: ${APP_SLUG}_database
    volumes:
      - ./storage-db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

  # Phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8585:80"
    container_name: ${APP_SLUG}_phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: ${DB_HOST}
    networks:
      - app_network

  # Mailhog Service
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    container_name: ${APP_SLUG}_mailhog
    environment:
      SERVICE_TAGS: ${APP_ENV}
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge